# ============================================================
# SonarCloud — Hardware Service (Python 3 / Raspberry Pi)
# ============================================================
sonar.projectKey=Abdelhamid108_ema2a-hardware
sonar.organization=abdelhamid108
sonar.projectName=Ema2a Hardware Service

# Source & language
sonar.sources=.
sonar.language=py
sonar.python.version=3

# Exclusions
sonar.exclusions=**/__pycache__/**,**/*.pyc
